CREATE DATABASE IF NOT EXISTS motorstock_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE motorstock_db;

CREATE TABLE IF NOT EXISTS stores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  location VARCHAR(180) DEFAULT NULL,
  tier VARCHAR(40) NOT NULL DEFAULT 'Silver',
  performance_rating INT NOT NULL DEFAULT 70
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  username VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(120) NOT NULL,
  user_type ENUM('admin','staff') NOT NULL DEFAULT 'staff',
  role VARCHAR(80) NOT NULL,
  shift ENUM('A','B') DEFAULT NULL,
  store_id INT NULL,
  active TINYINT(1) NOT NULL DEFAULT 0,
  frozen TINYINT(1) NOT NULL DEFAULT 0,
  FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bikes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  brand VARCHAR(120) DEFAULT NULL,
  category VARCHAR(80) NOT NULL,
  showroom_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  price_unit VARCHAR(20) NOT NULL DEFAULT 'lakhs',
  purchase_cost DECIMAL(10,2) NOT NULL DEFAULT 0,
  cost_unit VARCHAR(20) NOT NULL DEFAULT 'lakhs',
  gst_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
  margin_percent DECIMAL(7,2) NOT NULL DEFAULT 0,
  discount_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
  stock_units INT NOT NULL DEFAULT 0,
  sold_units INT NOT NULL DEFAULT 0,
  display_status VARCHAR(60) NOT NULL DEFAULT 'In Stock',
  chassis_vin VARCHAR(100) DEFAULT NULL,
  engine_serial VARCHAR(100) DEFAULT NULL,
  plate VARCHAR(80) DEFAULT NULL,
  color_scheme VARCHAR(100) DEFAULT NULL,
  odometer VARCHAR(80) DEFAULT NULL,
  fuel_model VARCHAR(40) DEFAULT NULL,
  model_year VARCHAR(12) DEFAULT NULL,
  registration_state VARCHAR(80) DEFAULT NULL,
  media_name VARCHAR(180) DEFAULT NULL,
  media_type VARCHAR(80) DEFAULT NULL,
  media_data LONGTEXT DEFAULT NULL,
  last_service_date DATE DEFAULT NULL,
  owner VARCHAR(140) NOT NULL DEFAULT 'Motorstock Network',
  insurance VARCHAR(140) NOT NULL DEFAULT 'Active',
  low_threshold INT NOT NULL DEFAULT 2,
  store_id INT NULL,
  created_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS sales (
  id INT AUTO_INCREMENT PRIMARY KEY,
  transaction_id VARCHAR(60) NOT NULL UNIQUE,
  customer_name VARCHAR(140) NOT NULL,
  phone VARCHAR(40) DEFAULT NULL,
  bike_name VARCHAR(160) NOT NULL,
  amount_lakh DECIMAL(10,2) NOT NULL,
  gst_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
  discount_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  status VARCHAR(80) NOT NULL,
  payment_status VARCHAR(80) NOT NULL,
  payment_mode VARCHAR(100) NOT NULL,
  store_id INT NULL,
  employee_id INT NULL,
  sale_date DATE NOT NULL,
  FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE SET NULL,
  FOREIGN KEY (employee_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS billing_invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_number VARCHAR(60) NOT NULL UNIQUE,
  transaction_type VARCHAR(40) NOT NULL,
  booking VARCHAR(10) NOT NULL DEFAULT 'No',
  customer_type VARCHAR(40) NOT NULL DEFAULT 'Individual',
  customer_name VARCHAR(140) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  email VARCHAR(140) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  city VARCHAR(80) DEFAULT NULL,
  state_name VARCHAR(80) DEFAULT NULL,
  pincode VARCHAR(20) DEFAULT NULL,
  id_type VARCHAR(60) DEFAULT NULL,
  id_reference VARCHAR(120) DEFAULT NULL,
  id_proof_file_name VARCHAR(180) DEFAULT NULL,
  id_proof_file_data LONGTEXT DEFAULT NULL,
  customer_gstin VARCHAR(40) DEFAULT NULL,
  customer_pan VARCHAR(40) DEFAULT NULL,
  relation_name VARCHAR(140) DEFAULT NULL,
  bill_to_address TEXT DEFAULT NULL,
  delivery_address TEXT DEFAULT NULL,
  bike_id INT NULL,
  bike_name VARCHAR(160) NOT NULL,
  category VARCHAR(80) DEFAULT NULL,
  color VARCHAR(100) DEFAULT NULL,
  vin VARCHAR(100) DEFAULT NULL,
  engine VARCHAR(100) DEFAULT NULL,
  model_year VARCHAR(12) DEFAULT NULL,
  fuel_type VARCHAR(40) DEFAULT NULL,
  odometer VARCHAR(80) DEFAULT NULL,
  showroom_price_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  quantity INT NOT NULL DEFAULT 1,
  accessories_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  insurance_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  registration_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  handling_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  logistics_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  extended_warranty_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  other_charges_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  subtotal_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  discount_type VARCHAR(40) NOT NULL DEFAULT 'None',
  discount_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  discount_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  taxable_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  gst_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
  gst_amount_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  cgst_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
  cgst_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  sgst_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
  sgst_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  round_off_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  grand_total_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  payment_status VARCHAR(80) NOT NULL,
  payment_mode VARCHAR(100) NOT NULL,
  payment_reference VARCHAR(160) DEFAULT NULL,
  payment_date DATE DEFAULT NULL,
  amount_paid_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  balance_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  booking_number VARCHAR(60) DEFAULT NULL,
  booking_amount_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  booking_date DATE DEFAULT NULL,
  expected_delivery_date DATE DEFAULT NULL,
  booking_status VARCHAR(80) DEFAULT NULL,
  finance_required VARCHAR(10) NOT NULL DEFAULT 'No',
  finance_provider VARCHAR(140) DEFAULT NULL,
  loan_amount_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  loan_application_number VARCHAR(120) DEFAULT NULL,
  loan_account_number VARCHAR(120) DEFAULT NULL,
  down_payment_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  loan_tenure_months INT NOT NULL DEFAULT 0,
  interest_rate_percent DECIMAL(6,2) NOT NULL DEFAULT 0,
  finance_status VARCHAR(80) DEFAULT NULL,
  emi_amount_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  emi_start_date DATE DEFAULT NULL,
  emi_due_date DATE DEFAULT NULL,
  emi_due_day INT NOT NULL DEFAULT 0,
  emi_frequency VARCHAR(40) NOT NULL DEFAULT 'Monthly',
  number_of_emis INT NOT NULL DEFAULT 0,
  emis_paid INT NOT NULL DEFAULT 0,
  remaining_emis INT NOT NULL DEFAULT 0,
  emi_status VARCHAR(40) NOT NULL DEFAULT 'Upcoming',
  next_emi_due_date DATE DEFAULT NULL,
  delivery_status VARCHAR(80) NOT NULL DEFAULT 'Pending',
  actual_delivery_date DATE DEFAULT NULL,
  delivery_location VARCHAR(160) DEFAULT NULL,
  sales_executive VARCHAR(140) DEFAULT NULL,
  store_id INT NULL,
  employee_id INT NULL,
  sale_id INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (bike_id) REFERENCES bikes(id) ON DELETE SET NULL,
  FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE SET NULL,
  FOREIGN KEY (employee_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS sale_status_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sale_id INT NOT NULL,
  status VARCHAR(80) NOT NULL,
  notes VARCHAR(255) DEFAULT NULL,
  changed_by INT NULL,
  changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE,
  FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS billing_payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_id INT NOT NULL,
  sale_id INT NULL,
  booking_number VARCHAR(60) DEFAULT NULL,
  customer_name VARCHAR(140) NOT NULL,
  bike_id INT NULL,
  store_id INT NULL,
  employee_id INT NULL,
  payment_type VARCHAR(80) NOT NULL,
  payment_mode VARCHAR(100) NOT NULL,
  amount_lakh DECIMAL(10,2) NOT NULL DEFAULT 0,
  reference VARCHAR(160) DEFAULT NULL,
  payment_date DATE DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (invoice_id) REFERENCES billing_invoices(id) ON DELETE CASCADE,
  FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE SET NULL,
  FOREIGN KEY (bike_id) REFERENCES bikes(id) ON DELETE SET NULL,
  FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE SET NULL,
  FOREIGN KEY (employee_id) REFERENCES users(id) ON DELETE SET NULL
);

INSERT IGNORE INTO stores (name, location, tier, performance_rating) VALUES
('Vizag Showroom', 'Visakhapatnam', 'Platinum', 95),
('Hyderabad Center', 'Hyderabad', 'Gold', 82),
('Vijayawada Hub', 'Vijayawada', 'Gold', 74),
('Guntur Outlet', 'Guntur', 'Silver', 62);

INSERT IGNORE INTO users (emp_id, name, username, password, user_type, role, shift, store_id, active) VALUES
('ADM-001', 'Network Admin', 'admin@gmail.com', 'admin', 'admin', 'Network Admin', NULL, NULL, 0),
('EMP-VZG-101', 'Anand Kumar', 'vizag_a', 'staff123', 'staff', 'Sales Executive', 'A', 1, 0),
('EMP-VZG-102', 'Rajesh K.', 'rajesh_b', 'staff123', 'staff', 'Senior Lead', 'B', 1, 0),
('EMP-HYD-201', 'Neha Reddy', 'hyd_a', 'staff123', 'staff', 'Finance Executive', 'A', 2, 0);

INSERT IGNORE INTO bikes (name, category, showroom_price, price_unit, purchase_cost, cost_unit, gst_percent, margin_percent, stock_units, sold_units, display_status, store_id, model_year, low_threshold) VALUES
('Ducati Panigale V4 R', 'Superbike', 48.50, 'lakhs', 39.20, 'lakhs', 28, 23.72, 4, 2, 'In Stock', 1, '2026', 2),
('BMW S 1000 RR', 'Sport', 24.20, 'lakhs', 19.40, 'lakhs', 28, 24.74, 2, 1, 'Low Stock', 2, '2026', 2),
('Kawasaki Ninja H2R', 'Track Only', 79.80, 'lakhs', 68.10, 'lakhs', 28, 17.18, 1, 1, 'Low Stock', 3, '2026', 2),
('Ducati Monster SP', 'Naked', 15.90, 'lakhs', 12.20, 'lakhs', 28, 30.33, 8, 3, 'In Stock', 4, '2026', 2);

INSERT IGNORE INTO sales (transaction_id, customer_name, phone, bike_name, amount_lakh, gst_percent, discount_lakh, status, payment_status, payment_mode, store_id, employee_id, sale_date) VALUES
('BIKE-2026-9842', 'Vikram Rathore', '+91 98492 83920', 'Ducati Panigale V4 R', 48.50, 28, 0, 'Delivered', 'Paid', 'NEFT / RTGS / Bank Transfer', 1, 3, '2026-08-12'),
('BIKE-2026-7731', 'Anya Reddy', '+91 90000 11122', 'BMW S 1000 RR', 24.20, 28, 0, 'Pending Finance', 'Down Payment', 'UPI + Finance', 2, 4, '2026-08-19'),
('BIKE-2026-8199', 'Devendra Naidu', '+91 90000 33344', 'Kawasaki Ninja H2R', 79.80, 28, 0, 'Delivered', 'Paid', 'Bank Transfer', 3, 2, '2026-08-25');
